AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SES email sender via Lambda + API Gateway

Resources:
  EmailSenderLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-custom-lambda-email-ses
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      Events:
        SendEmailAPI:
          Type: Api
          Properties:
            Path: /send-email
            Method: post
